eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8013/eureka
    #设为true，开启健康检查（需要sping-boot-start-actuator依赖）
    healthcheck:
      enabled: true
    #加快从eureka服务器注册表中获取注册信息的时间间隔
    registryFetchIntervalSeconds: 5
  instance:
    #使用ip替代实例名
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: "root"         #These two are needed so that the server
      user.password: "1234"  #can access the protected client endpoints

management:
  endpoints:
    web:
      #      由于 Spring Boot 2.0 的 Actuator 只暴露了 /health、/info 两个端口（为了安全考虑）, 所以需要配置暴露的接口
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


spring:
  security:
    user:
      name: "root"
      password: "1234"