spring:
  application:
    name: lp-grpc-server
  cloud:
    sentinel:
      transport:
        #Sentinel 控制台地址
        dashboard: localhost:8080
      #取消Sentinel控制台懒加载
      eager: true

grpc:
  server:
    port: 9898

server:
  port: 8016

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8013/eureka
  instance:
    prefer-ip-address: true
    metadata-map:
      description: 这是一个消费者

