spring:
  security:
    user:
      name: root
      password: 123456

#是否把自己注册到Eureka
  eureka.client.register-with-eureka=false
  #是否从Eureka获取注册信息(单Eureka为false)
  eureka.client.fetch-registry=false

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    #是否把自己注册到Eureka
    register-with-eureka: false
    #是否从Eureka获取注册信息(单Eureka为false)
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #关闭注册中心的保护机制，不然服务上线不能及时发现
    enable-self-preservation: false